import type { CampaignTemplate } from "./schemas";

export const campaignTemplates: CampaignTemplate[] = [
  {
    id: "beverage-launch",
    name: "Beverage launch",
    description: "Two-week creator-led launch for a new beverage product with social proof and challenge mechanics.",
    brief: {
      brandName: "",
      productOrService: "sparkling energy drink",
      campaignGoal: "Launch a two-week creator campaign that drives trial, social participation, and qualified site visits among Gen Z audiences.",
      targetAudience: "Gen Z students and young professionals interested in fitness, gaming, and lifestyle content",
      audienceSegments: ["Gen Z students", "young fitness creators", "gaming community"],
      market: "United States",
      budgetRange: "$40k-$60k",
      channels: ["TikTok", "Instagram", "YouTube Shorts"],
      timelineWeeks: 2,
      constraints: "Avoid medical claims and keep creator language flexible for authenticity.",
      brandVoice: "direct, energetic, and culturally fluent",
      competitors: ["Red Bull", "Celsius", "Liquid Death"],
      creatorCriteria: "Creators must have audience trust, short-form skill, category adjacency in fitness or lifestyle, and low brand-safety risk.",
      successMetrics: ["qualified site visits", "creator comment quality", "completion rate"],
      mandatoryMessages: ["zero sugar energy without a crash", "built for busy routines"],
      forbiddenClaims: ["instant results", "100% safe", "medical benefit"],
      approvalRequirements: "Legal must approve product claims and brand must approve creator scripts before publication.",
      knowledgeNotes: "Past campaigns performed best when creators showed realistic routines and answered objections in comments.",
    },
  },
  {
    id: "beauty-product-launch",
    name: "Beauty product launch",
    description: "Creator-first beauty launch focused on authentic tutorials, before-and-after proof, and community engagement.",
    brief: {
      brandName: "",
      productOrService: "clean beauty skincare line",
      campaignGoal: "Drive product trial and brand awareness through authentic creator tutorials and community-driven content across Instagram and TikTok.",
      targetAudience: "Women 18-34 interested in clean beauty, skincare routines, and self-care content",
      audienceSegments: ["skincare enthusiasts", "beauty creators", "clean beauty advocates"],
      market: "United States",
      budgetRange: "$50k-$80k",
      channels: ["TikTok", "Instagram", "YouTube Shorts"],
      timelineWeeks: 3,
      constraints: "All claims must be dermatologist-approved. No before-and-after editing allowed.",
      brandVoice: "warm, educational, and empowering",
      competitors: ["Glossier", "The Ordinary", "Drunk Elephant"],
      creatorCriteria: "Beauty creators with 50k-500k followers, authentic skincare routines, and high engagement rates.",
      successMetrics: ["product page visits", "save rate", "user-generated content volume"],
      mandatoryMessages: ["dermatologist tested", "clean ingredients", "real results in 4 weeks"],
      forbiddenClaims: ["instant transformation", "cures skin conditions", "better than prescription"],
      approvalRequirements: "All content requires brand and legal review. Before-and-after must be unedited and timestamped.",
      knowledgeNotes: "Audience responds to honest reviews and routine integration rather than hard-sell content.",
    },
  },
  {
    id: "app-growth",
    name: "App growth campaign",
    description: "Performance-focused campaign to drive app installs and activation through creator content and paid amplification.",
    brief: {
      brandName: "",
      productOrService: "productivity mobile app",
      campaignGoal: "Drive 10,000 qualified app installs with 40% activation rate within 4 weeks through creator content and paid social amplification.",
      targetAudience: "Professionals 25-40 looking for productivity tools and workflow optimization",
      audienceSegments: ["remote workers", "freelancers", "startup founders"],
      market: "Global (English-speaking)",
      budgetRange: "$30k-$50k",
      channels: ["TikTok", "Instagram", "LinkedIn"],
      timelineWeeks: 4,
      constraints: "Must include app store link in all content. Paid boost must target lookalike audiences.",
      brandVoice: "smart, practical, and slightly witty",
      competitors: ["Notion", "Todoist", "Linear"],
      creatorCriteria: "Tech and productivity creators with demonstrated ability to drive app installs, not just views.",
      successMetrics: ["app installs", "activation rate", "cost per install", "day-7 retention"],
      mandatoryMessages: ["save 2 hours per week", "integrates with your existing tools", "free to start"],
      forbiddenClaims: ["replaces all other tools", "guaranteed productivity increase", "AI does everything"],
      approvalRequirements: "All app screenshots must show current UI. Performance claims require data backing.",
      knowledgeNotes: "Install campaigns work best with demo-style content showing real workflows rather than feature lists.",
    },
  },
  {
    id: "b2b-creator",
    name: "B2B creator campaign",
    description: "LinkedIn and thought-leadership focused campaign using industry creators to build pipeline and brand authority.",
    brief: {
      brandName: "",
      productOrService: "B2B analytics platform",
      campaignGoal: "Generate 200 qualified leads and build thought leadership positioning through industry creator partnerships on LinkedIn and YouTube.",
      targetAudience: "Marketing and analytics leaders at mid-market companies evaluating data platforms",
      audienceSegments: ["VP Marketing", "Head of Analytics", "Marketing Operations managers"],
      market: "North America",
      budgetRange: "$25k-$40k",
      channels: ["LinkedIn", "YouTube Shorts"],
      timelineWeeks: 4,
      constraints: "Content must be educational, not promotional. All data claims must cite sources.",
      brandVoice: "authoritative, data-driven, and approachable",
      competitors: ["HubSpot", "Looker", "Amplitude"],
      creatorCriteria: "B2B thought leaders with 10k+ LinkedIn followers, analytics or marketing backgrounds, and high-quality long-form content.",
      successMetrics: ["qualified leads", "demo requests", "content engagement rate", "share of voice"],
      mandatoryMessages: ["unified data without engineering overhead", "built for marketing teams", "SOC 2 compliant"],
      forbiddenClaims: ["replaces your data team", "zero setup time", "guaranteed ROI"],
      approvalRequirements: "All content requires product marketing and legal review. Case study references need customer approval.",
      knowledgeNotes: "B2B buyers respond to peer validation and specific use cases rather than feature comparisons.",
    },
  },
];
