import Link from "next/link";

export const metadata = {
  title: "Terms of Use - Pilot",
  description: "Terms of use for Pilot, covering acceptable use, liability, and intellectual property.",
};

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="legal-content">
        <Link href="/" className="legal-back">&larr; Back to home</Link>
        <h1 className="legal-title">Terms of Use</h1>
        <p className="legal-updated">Last updated: June 2026</p>

        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using Pilot (&ldquo;the Platform&rdquo;), you agree to be bound by these Terms of Use (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the Platform. These Terms apply to all users, including without limitation users who are browsers, contributors, or campaign creators.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Service</h2>
          <p>
            Pilot is an AI-powered marketing campaign planning and management platform. It provides tools for creating campaign briefs, running AI agents to generate strategies, managing campaign tasks through a command center, and evaluating campaign outputs. The Platform is provided as a portfolio demonstration project.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. Eligibility</h2>
          <p>
            You must be at least 16 years old to use Pilot. By using the Platform, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. Account and Data</h2>
          <p>
            Pilot stores campaign data locally in your browser&rsquo;s localStorage. You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of any API keys you configure</li>
            <li>All activities that occur under your browser session</li>
            <li>Backing up your campaign data, as localStorage data may be lost if you clear browser data</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>5. Acceptable Use</h2>
          <p>You agree not to use Pilot to:</p>
          <ul>
            <li>Violate any applicable law, regulation, or third-party rights</li>
            <li>Generate campaigns containing false, misleading, or deceptive claims</li>
            <li>Create content that is defamatory, obscene, or otherwise objectionable</li>
            <li>Infringe on intellectual property rights of others</li>
            <li>Attempt to gain unauthorized access to the Platform or its systems</li>
            <li>Use the Platform for spam, phishing, or other malicious activities</li>
            <li>Reverse engineer, decompile, or disassemble the Platform</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>6. AI-Generated Content</h2>
          <p>
            Campaign strategies, calendars, creator recommendations, and other outputs generated by Pilot&rsquo;s AI agents are provided for planning purposes only. You are solely responsible for:
          </p>
          <ul>
            <li>Reviewing and approving all AI-generated content before use</li>
            <li>Ensuring that campaign content complies with applicable advertising laws and regulations</li>
            <li>Verifying factual claims made in campaign materials</li>
            <li>Obtaining necessary rights and permissions for any content you publish</li>
          </ul>
          <p>
            Pilot does not guarantee the accuracy, completeness, or suitability of AI-generated outputs.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Intellectual Property</h2>
          <p>
            The Pilot platform, including its code, design, and branding, is the intellectual property of the project maintainer. Campaign data you create remains yours. You grant Pilot a limited license to process your data solely for the purpose of providing the Platform&rsquo;s services.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Third-Party Services</h2>
          <p>
            Pilot may integrate with third-party AI providers (Anthropic, OpenAI-compatible endpoints). Your use of these services is subject to their respective terms of service and privacy policies. Pilot is not responsible for the availability, accuracy, or practices of third-party services.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Disclaimer of Warranties</h2>
          <p>
            THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. PILOT DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE.
          </p>
        </section>

        <section className="legal-section">
          <h2>10. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, PILOT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE PLATFORM. PILOT&rsquo;S TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR USE OF THE PLATFORM IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.
          </p>
        </section>

        <section className="legal-section">
          <h2>11. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Pilot and its maintainers from and against any claims, liabilities, damages, losses, and expenses arising out of or in any way connected with your use of the Platform, violation of these Terms, or infringement of any third-party rights.
          </p>
        </section>

        <section className="legal-section">
          <h2>12. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your access to the Platform at any time, with or without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. You may stop using the Platform at any time by clearing your browser data.
          </p>
        </section>

        <section className="legal-section">
          <h2>13. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the Federative Republic of Brazil, including the Brazilian Civil Code and the LGPD (Law No. 13.709/2018), without regard to its conflict of law provisions. For users in the European Economic Area, GDPR (Regulation (EU) 2016/679) also applies.
          </p>
        </section>

        <section className="legal-section">
          <h2>14. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting to this page. Your continued use of the Platform after changes constitutes acceptance of the modified Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>15. Contact</h2>
          <p>
            For questions about these Terms, please contact us through the project repository at{" "}
            <a href="https://github.com/anomalyco/opencode/issues" target="_blank" rel="noopener noreferrer">GitHub</a>.
          </p>
        </section>
      </div>
    </main>
  );
}
